### ISSUE TITLE
PR to provide enhancements to upstream

### ISSUE THREAD

**Issue by tyler-ball** [chef/go-chef#20]
# Describe the problem
We added support for some new server endpoints and we want to contribute these back to the upstream. 

Related issue: https://github.com/chef/go-chef/issues/15

# Acceptance Criteria
* Rebase our fork off the upstream master, resolve any conflicts
    * We know the upstream maintainer has been manually porting over *some* of the changes we have made
* Contribute any changes in our fork back to the upstream if they are not present there yet

# Notes
The upstream has changed how they perform Test Kitchen tests, so rebasing off that is likely a manual process. But we want to have testing on any feature we add at the same level as it is tested in the upstream.

Known differences:
* Code changes (new endpoints)
* Unit tests
* Existing Test Kitchen tests (we changed how we perform TK tests in our fork)
* New TK tests for new endpoints

**Comment by MarkGibbons** [comment]
https://github.com/go-chef/chef/pull/191  should handle pushing your changes for April back upstream.  thanks for the updates.

**Comment by mudash** [comment]
Opened #24 to discuss / resolve a concern about cookbook download functionality.

**Comment by marcparadise** [comment]
https://github.com/go-chef/chef/pull/210 is the work in progress. I attempted this as straight merge of chef/master into go-chef/master to try to reduce the pain of rebasing a couple hundred commits , but results are mixed, with pain as expected around the change in test structure. 

  I'm taking a shot at this with rebase to compare, maybe it'll be easier than I expect...
