### ISSUE TITLE
Document cookbook_artifact API endpoints

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/go-chef#22]
# Describe the problem

Write documentation on the https://github.com/chef/chef-web-docs/blob/master/content/api_chef_server.md page for the `/organization/*/cookbook_artifacts/*` endpoints.

[Here](https://github.com/chef/chef-server/blob/46a219466bd287ff6365fc83e4dfbcd2c823d447/src/oc_erchef/apps/oc_chef_wm/itest/oc_chef_wm_cookbook_artifact_SUITE.erl#L376) is one place where the API is tested revealing some of its structures.

[Here](https://github.com/chef/chef-server/blob/ac11df3d7c88b164a16beccdd18c12d403e87967/src/oc_erchef/apps/oc_chef_wm/src/oc_chef_wm_named_cookbook_artifact_version.erl) is the implementation of the `cookbook_artifacts/NAME/ID` handler.

Related: #19 and #21 implement the API in this library.

## Acceptance Criteria

1. The Chef Server API documentation contains documentation for for the endpoints `cookbook_artifacts`, `cookbook_artifacts/NAME`, and `cookbook_artifacts/NAME/ID` for the GET verb.
2. The endpoints are documented for the DELETE, and PUT verbs as applicable.

**Comment by tyler-ball** [comment]
Merged!
