### ISSUE TITLE
Partial Search Errors when number of nodes > 1000

### ISSUE THREAD

**Issue by mudash** [chef/go-chef#27]
During nodes report generation we query Chef Server for nodes and their related attributes. While testing this against a Chef Server that has more than 1000 nodes, the following error showed up:

`Error: unable to get node(s) information: POST https://54.183.139.36/organizations/my-org/search/node?q=%2A%3A%2A&rows=1000&sort=X_CHEF_id_CHEF_X+asc&start=1000: 400`

Upon research it was found that we call the Chef Server to retrieve first 1000 nodes without a problem but the second call to retrieve remaining nodes generates this error

**Comment by MarkGibbons** [comment]
In the search.go module in func  PartialExec.  "body" is initialized to JSONReader(params) and used by the first POST call.   In the loop for subsequent POST calls to get the rest of the search body is used but not initialized or reset.  The body reader is empty when used in the for loop and causes the 400 returns.  I should have a fix later today.  

That's one of the modules where I did not finish the tests against a live chef server.  The searches will fail any time the for loop is used to get values. 1000 is not really a magic number for the failure despite being hardcoded almost everywhere.

**Comment by MarkGibbons** [comment]
https://github.com/go-chef/chef/commit/f1d93d27f2fb73f89e7af5b62e1c528e195ab616 if you want to cherry-pick the fix.
